### ISSUE TITLE
[crash] Unit Conversion error

### ISSUE THREAD

**Issue by matemargit** [webmaster442/Thingy#20]
When I tried to open the "Unit Conversion" in Calculator, I got the following error:
Update: I got this in "Display Result as Text" option, too.

![kep](https://user-images.githubusercontent.com/18399908/38929080-76c9bd42-430b-11e8-899f-9fdd461b712c.png)

![kep](https://user-images.githubusercontent.com/18399908/38929129-a225d14c-430b-11e8-963f-9ebee413b0ea.png)

Full reproducation flow:
- I started the program from Visual Studio
- I selected the Calculator
- I clicked the "Unit Conversation" icon

![error](https://user-images.githubusercontent.com/18399908/38934908-39086492-431d-11e8-8501-d8a3f1fa6626.png)

- After this, I got this exception in code:

![kep](https://user-images.githubusercontent.com/18399908/38934966-6953308c-431d-11e8-9b57-7156cda2bfa6.png)

- I clicked the "Continue" in VS
- I heard an error sound, and I saw the error message:

![kep](https://user-images.githubusercontent.com/18399908/38935053-999d9fde-431d-11e8-8341-98ddd198dab2.png)

- I clicked the "OK" button, and I got another exception:

![kep](https://user-images.githubusercontent.com/18399908/38935105-bb509b04-431d-11e8-9f1c-d44e8d50ce6d.png)

- I clicked the "Continue" again and the program closed.

**Comment by webmaster442** [comment]
Fixed
